services:
  redis:
    image: redis:7
    container_name: blob-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: blob-postgres
    environment:
      POSTGRES_USER: blob
      POSTGRES_PASSWORD: blob
      POSTGRES_DB: blob_storage
    ports:
      - "5432:5432"
    volumes:
     - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: 